spring:
  application:
    name: vapor-back
  security:
    user:
      name: user
      password: password
  data:
    mongodb:
      autoIndexCreation: true
      authentication-database: admin
      username: root
      password: pass12345
      database: steamdb
      port: 27017
      host: localhost
  mail:
    host: smtp.office365.com
    port: 587
    username: ingwebproyecto@outlook.com
    password: qvjlrtwlzfbpghcp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true




