spring:
  application:
    name: vapor-back
  security:
    user:
      name: user
      password: password
  data:
    mongodb:
      autoIndexCreation: true
      authentication-database: admin
      username: root
      password: pass12345
      database: steamdb
      port: 27017
      host: localhost
  mail:
    host: smtp.gmail.com
    port: 587
    username: marcos.funcky@gmail.com
    password: Googleylareputaquetepario159357486.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true




