spring:
  application:
    name: vapor-back
  security:
    user:
      name: user
      password: password
  data:
    mongodb:
      autoIndexCreation: true
      authentication-database: admin
      username: root
      password: pass12345
      database: steamdb
      port: 27017
      host: localhost




